feedback-delayed_deadline
Ordering-Inc/Ordering-UI-Native pull request #734
Opened 2022-04-22 20:54 UTC by mingxue-ordering

story: https://app.asana.com/0/1200550251832819/1202141091343461

2022-04-22 21:51 UTC, carlosq-ordering requested changes
Please provide somes captures, images or vids, thanks

2022-04-22 21:51 UTC, carlosq-ordering commented on example/themes/business/src/components/OrdersOption/index.tsx
> +      <OText>min</OText>
Don't hardcode the text

2022-04-23 06:50 UTC, mingxue-ordering commented
Demo: https://d.pr/i/bYsyxj

2022-04-23 06:52 UTC, mingxue-ordering commented
> Please provide somes captures, images or vids, thanks

Demo: https://d.pr/i/bYsyxj

2022-04-23 16:07 UTC, carlosq-ordering approved these changes

2022-04-23 16:07 UTC, merged